### ISSUE TITLE
您好, 您代码可能存在一些问题

### ISSUE THREAD

**Issue by Frankaiyou** [miskcoo/programming-training#1]
我的Qt版本是5.6.3, MinGW版本是4.9.2, 在编译您的代码 (Sudoku) 时出现了一些问题, 发现`QAction`类不存在一个只传`QString`参数的构造函数, 至少还需要传一个$parent$指针.
`QAction(const QString &text, QObject* parent);`

**Comment by miskcoo** [comment]
我这边应该是 5.7.0，不清楚什么时候更新的，至少现在最新版这个 parent 有默认值 nullptr
https://doc.qt.io/qt-5/qaction.html
